<a href="https://colab.research.google.com/github/vijay580/NEW/blob/master/Copy_of_Copy_of_Untitled5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:


import tensorflow as tf
import cv2
import os
import numpy as np
from tensorflow.contrib.learn.python.learn.datasets.mnist import extract_images, extract_labels
import time
import matplotlib.pyplot as plt
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from google.colab import drive
import pandas as pd
from tensorflow.keras import backend as K
from google.colab.patches import cv2_imshow
drive.mount('/content/gdrive', force_remount=True)
root_dir = "/content/gdrive/My Drive/"
base_dir = root_dir + 'cnn/'
path=base_dir


df      = pd.read_csv(base_dir+'train_files.csv')
name    = df.file_name.tolist()
rating  = df.annotation.tolist()
print (name)
print (rating)
#print (name.shape)
#print(type(name))

import tensorflow as tf
import cv2
import os
import numpy as np
import glob
from tensorflow.contrib.learn.python.learn.datasets.mnist import extract_images, extract_labels
import time
#from keras.constraints import max_norm
import matplotlib.pyplot as plt
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from google.colab import drive
import pandas as pd
from tensorflow.keras import backend as K
from google.colab.patches import cv2_imshow
drive.mount('/content/gdrive', force_remount=True)
root_dir = "/content/gdrive/My Drive/"
base_dir = root_dir + 'cnn/'
path=base_dir

filenames = glob.glob(base_dir+'Project_C2_Testing/*.jpg')
filenames.sort()
images=[cv2.imread(img) for img in filenames]
images = [cv2.resize(img,(128,128)) for img in images]
images = [img/255 for img in images]
for img in filenames:
  print (img)
  
images = np.array(images)
print(images.shape)  


  


 





Mounted at /content/gdrive
['000006.jpg', '000016.jpg', '000032.jpg', '000097.jpg', '000104.jpg', '000122.jpg', '000237.jpg', '000253.jpg', '000265.jpg', '000300.jpg', '000306.jpg', '000333.jpg', '000339.jpg', '000353.jpg', '000387.jpg', '000401.jpg', '000424.jpg', '000470.jpg', '000478.jpg', '000479.jpg', '000488.jpg', '000555.jpg', '000608.jpg', '000635.jpg', '000675.jpg', '000698.jpg', '000704.jpg', '000710.jpg', '000738.jpg', '000758.jpg', '000770.jpg', '000778.jpg', '000780.jpg', '000821.jpg', '000876.jpg', '000917.jpg', '000941.jpg', '000957.jpg', '000979.jpg', '000981.jpg', '001010.jpg', '001027.jpg', '001038.jpg', '001064.jpg', '001106.jpg', '001118.jpg', '001150.jpg', '001163.jpg', '001182.jpg', '001197.jpg', '001213.jpg', '001217.jpg', '001219.jpg', '001225.jpg', '001238.jpg', '001279.jpg', '001326.jpg', '001396.jpg', '001405.jpg', '001411.jpg', '001464.jpg', '001503.jpg', '001515.jpg', '001516.jpg', '001518.jpg', '001578.jpg', '001598.jpg', '001602.jpg', '001635.jpg', '00163

In [3]:
df      = pd.read_csv(base_dir+'train_files.csv')
name    = df.file_name.tolist()
rating  = df.annotation.tolist()
print (name)
print (rating)
#print (name.shape)
#print(type(name))

#print (len(name))
y=[]
print (len(rating))
for x in range(len(name)):
    print(x)
    image =cv2.imread(base_dir+'Training/'+name[x])
    image = cv2.resize(image,(128,128))
    image = image/255
    y.append(image)
#print(y)

print (len(y))

#print(y[10],name[10])
encoded = to_categorical(rating)
for i in range(0,25):
  print(encoded[0])
  
print (len(encoded))

#for x in range(len(encoded)):
#print(encoded[7])
x_train, x_val, y_train, y_val = train_test_split(y,encoded,test_size=0.2)




['000006.jpg', '000016.jpg', '000032.jpg', '000097.jpg', '000104.jpg', '000122.jpg', '000237.jpg', '000253.jpg', '000265.jpg', '000300.jpg', '000306.jpg', '000333.jpg', '000339.jpg', '000353.jpg', '000387.jpg', '000401.jpg', '000424.jpg', '000470.jpg', '000478.jpg', '000479.jpg', '000488.jpg', '000555.jpg', '000608.jpg', '000635.jpg', '000675.jpg', '000698.jpg', '000704.jpg', '000710.jpg', '000738.jpg', '000758.jpg', '000770.jpg', '000778.jpg', '000780.jpg', '000821.jpg', '000876.jpg', '000917.jpg', '000941.jpg', '000957.jpg', '000979.jpg', '000981.jpg', '001010.jpg', '001027.jpg', '001038.jpg', '001064.jpg', '001106.jpg', '001118.jpg', '001150.jpg', '001163.jpg', '001182.jpg', '001197.jpg', '001213.jpg', '001217.jpg', '001219.jpg', '001225.jpg', '001238.jpg', '001279.jpg', '001326.jpg', '001396.jpg', '001405.jpg', '001411.jpg', '001464.jpg', '001503.jpg', '001515.jpg', '001516.jpg', '001518.jpg', '001578.jpg', '001598.jpg', '001602.jpg', '001635.jpg', '001636.jpg', '001641.jpg', '0016

In [4]:
x_train = np.array(x_train)
print(x_train.shape)
y_train = np.array(y_train)
x_val = np.array(x_val)
y_val = np.array(y_val)
for i in range(0,25):
  print(encoded[i])

(716, 128, 128, 3)
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[0. 0. 0. 0. 1.]
[1. 0. 0. 0. 0.]
[0. 0. 0. 1. 0.]
[0. 0. 0. 0. 1.]
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[0. 0. 1. 0. 0.]
[0. 0. 1. 0. 0.]
[1. 0. 0. 0. 0.]
[0. 0. 1. 0. 0.]
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 0. 0. 1. 0.]
[0. 1. 0. 0. 0.]
[0. 0. 0. 0. 1.]
[0. 0. 0. 1. 0.]
[1. 0. 0. 0. 0.]
[0. 0. 0. 0. 1.]
[0. 0. 0. 1. 0.]
[0. 1. 0. 0. 0.]
[1. 0. 0. 0. 0.]


In [0]:
def train_mnist_conv(dense=512,dropout=0.4,activation='relu',eta=0.00146,maps=96,ksize=7,norm=2):
   
    class myCallback(tf.keras.callbacks.Callback):
        def on_epoch_end(self, epoch, logs={}):
            if(logs.get('acc')>0.998):
              #print("\nReached 99.8% accuracy so cancelling training!")
              self.model.stop_training = True

    
    callbacks = myCallback()
    model = tf.keras.models.Sequential([
            
            tf.keras.layers.Conv2D(maps, (ksize), activation=activation, input_shape=(128, 128, 3)),
            tf.keras.layers.BatchNormalization(),
        
            tf.keras.layers.Conv2D(maps, (ksize), activation=activation),
            tf.keras.layers.BatchNormalization(),
        
            tf.keras.layers.Conv2D(maps, (ksize+2),strides=2,padding='same', activation=activation),
            tf.keras.layers.BatchNormalization(),
            tf.keras.layers.Dropout(dropout),
        
            tf.keras.layers.Conv2D((maps*2), (ksize), activation=activation),
            tf.keras.layers.BatchNormalization(),
        
            tf.keras.layers.Conv2D((maps*2), (ksize), activation=activation),
            tf.keras.layers.BatchNormalization(),
        
            tf.keras.layers.Conv2D((maps*2), (ksize+2),strides=5,padding='same', activation=activation),
            tf.keras.layers.BatchNormalization(),
            tf.keras.layers.Dropout(dropout),
        
            tf.keras.layers.Flatten(),
        
            tf.keras.layers.Dense(dense, activation=activation,kernel_constraint=tf.keras.constraints.max_norm(norm)),
            tf.keras.layers.BatchNormalization(),
            tf.keras.layers.Dropout(dropout),
            tf.keras.layers.Dense(dense, activation=activation,kernel_constraint=tf.keras.constraints.max_norm(norm)),
        
            tf.keras.layers.BatchNormalization(),
            tf.keras.layers.Dropout(dropout),
        
            tf.keras.layers.Dense(5, activation='softmax')
    ])
    opt = tf.keras.optimizers.Adam(learning_rate=eta)
    model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])
    #model.summary()
    history = model.fit(
        x_train, y_train, epochs=36, #callbacks=[callbacks]
        validation_data=(x_val,y_val)
    )
    model.save(base_dir+'weights')
    if activation == 'relu':
       y_pred = model.predict(images)

    import pandas as pd
  #print(y_pred)
    for i, d in enumerate(y_pred):
        y_pred[i] = y_pred[i] // max(d)

    y_pred = np.array(y_pred, dtype=np.uint8)
# save data into csv file
#for i in y_onehot:
    save = pd.DataFrame(y_pred, columns=[0, 1, 2, 3, 4])
    save.to_csv(path+'new.csv', index=False, header=False) 
    f.write("\n --------------------new--------------------")
  #(dense=128,dropout=0.4,activation='relu',eta=0.001,maps=32,ksize=3)
  

    f.write("\n Denselayer: ")
    f.write(str(dense))
    f.write("\n Dropout: ")
    f.write(str(dropout))
    f.write("\n Activation: ")
    f.write(str(activation))
    f.write("\n Learning Rate: ")
    f.write(str(eta))
    f.write("\n Maps: ")
    f.write(str(maps))
    f.write("\n kernel size: ")
    f.write(str(ksize))
   
    
    f.write("\n Training_Loss: ")
    f.write(str(history.history['loss'][-1]))
    f.write("\n Training_acc: ")
    f.write(str(history.history['acc'][-1]))
    f.write("\n Valid_Loss: ")
    f.write(str(history.history['val_loss'][-1]))
    f.write("\n Valid_acc: ")
    f.write(str(history.history['val_acc'][-1]))

    f.write("\n Training_Loss Complete: ")
    f.write(str(history.history['loss']))
    f.write("\n Training_acc Complete: ")
    f.write(str(history.history['acc']))
    f.write("\n Valid_Loss Complete: ")
    f.write(str(history.history['val_loss']))
    f.write("\n Valid_acc Complete: ")
    f.write(str(history.history['val_acc']))
    
    
    return history.epoch, history.history['acc'], history.history['val_acc'],history.history['loss'],history.history['val_loss']


In [6]:
if __name__ == "__main__":
  
  filename = time.strftime("%Y%m%d-%H%M%S")
  f = open(path+'datafor'+filename,"w+") 
  
  #train_mnist_conv(dense=128,dropout=0.4,activation='relu',eta=0.0005,maps=32,ksize=3)
  
  
  #(dense=128,dropout=0.4,activation='relu',eta=0.001,maps=32,ksize=3)
  import matplotlib.pyplot as plt
  DenseList = [32,64,128,256,512]
  etaList = [0.01,0.001,0.0001,0.0005,0.00146]
  mapsList = [24,48,64,96,128]
  ksizeList = [3,5,7,9,11]
  DropoutList = [0.1,0.2,0.3,0.4,0.5,0.6,0.7]
  maxNormList =[1,2,3,4,5]

  for i in range(len(etaList)):
      n,t,v,l,vl = train_mnist_conv(eta=etaList[i])
      #print(i,n,t,v)
      plt.figure(1)
      plt.plot(list(range(0,len(t))),t, label=str(etaList[i]))
      plt.figure(2)
      plt.plot(list(range(0,len(v))),v, label=str(etaList[i]))
  plt.figure(1)
  legend = plt.legend(loc='lower right', shadow=True)
  plt.title("Training Accuracy: Learning Rate")
  plt.xlabel('Epoch')
  plt.ylabel('Accuracy')
  plt.savefig(path+'TrainingaccuracyLearningRate')
  plt.clf()
  plt.figure(2)
  
  legend = plt.legend(loc='lower right', shadow=True)
  plt.title("Validation Accuracy: Learning Rate")
  plt.xlabel('Epoch')
  plt.ylabel('Accuracy')
  plt.savefig(path+'Validationaccuracylearningrate')
  plt.clf()


  
 



  for i in range(len(DenseList)):
      n,t,v,l,vl= train_mnist_conv(dense=DenseList[i])
      #print('n',n,'t',t,'v',v)
      plt.figure(1)
      plt.plot(list(range(0,len(t))),t ,label=str(DenseList[i]))#, label=str(DenseList[i]))
      plt.figure(2)
      plt.plot(list(range(0,len(t))),v, label=str(DenseList[i]))#
  plt.figure(1)

  legend = plt.legend(loc='lower right', shadow=True)
  plt.title("Training Accuracy: Dense Layer")
  plt.xlabel('Epoch')
  plt.ylabel('Accuracy')
  plt.savefig(path+'Trainingaccuracydenselayer')
  plt.clf()

  plt.figure(2)

  legend = plt.legend(loc='lower right', shadow=True)
  plt.title("Validation Accuracy: Dense Layer")
  plt.xlabel('Epoch')
  plt.ylabel('Accuracy')
  plt.savefig(path+'Validationaccuracydenselayer')
  plt.clf()

  

  for i in range(len(mapsList)):
      n,t,v,l,vl = train_mnist_conv(maps=mapsList[i])
      plt.figure(1)
      plt.plot(list(range(0,len(t))),t, label=str(mapsList[i]))
      plt.figure(2)

      plt.plot(list(range(0,len(v))),v, label=str(mapsList[i]))

  plt.figure(1)
  legend = plt.legend(loc='lower right', shadow=True)
  plt.title("Training Accuracy: Feature Maps")
  plt.xlabel('Epoch')
  plt.ylabel('Accuracy')
  plt.savefig(path+'Trainingaccuracymaps')
  plt.clf()
  plt.figure(2)
  legend = plt.legend(loc='lower right', shadow=True)
  plt.title("Validation Accuracy: Feature Maps")
  plt.xlabel('Epoch')
  plt.ylabel('Accuracy')
  plt.savefig(path+'Validationaccuracymaps')
  plt.clf()


  for i in range(len(ksizeList)):
      n,t,v,l,vl = train_mnist_conv(ksize=ksizeList[i])
      plt.figure(1)
      plt.plot(list(range(0,len(t))),t, label=str(ksizeList[i]))
      plt.figure(2)
      plt.plot(list(range(0,len(v))),v, label=str(ksizeList[i]))
  plt.figure(1)
  legend = plt.legend(loc='lower right', shadow=True)
  plt.title("Training Accuracy: Kernel Size")
  plt.xlabel('Epoch')
  plt.ylabel('Accuracy')
  plt.savefig(path+'Trainingaccuracyksize')
  plt.clf()
  plt.figure(2)
  legend = plt.legend(loc='lower right', shadow=True)
  plt.title("Validation Accuracy: Kernel Size")
  plt.xlabel('Epoch')
  plt.ylabel('Accuracy')
  plt.savefig(path+'Validationaccuracyksize')
  plt.clf()

  for i in range(len(DropoutList)):
      n,t,v,l,vl = train_mnist_conv(dropout=DropoutList[i])
      plt.figure(1)
      plt.plot(list(range(0,len(t))),t, label=str(DropoutList[i]))
      plt.figure(2)
      plt.plot(list(range(0,len(v))),v, label=str(DropoutList[i]))
  plt.figure(1)
  legend = plt.legend(loc='lower right', shadow=True)
  plt.title("Training Accuracy: Dropout")
  plt.xlabel('Epoch')
  plt.ylabel('Accuracy')
  plt.savefig(path+'Trainingaccuracydropout')
  plt.clf()
  plt.figure(2)
  legend = plt.legend(loc='lower right', shadow=True)
  plt.title("Validation Accuracy: Dropout")
  plt.xlabel('Epoch')
  plt.ylabel('Accuracy')
  plt.savefig(path+'Validationaccuracydropout')
  plt.clf()
  
  for i in range(len(maxNormList)):
      n,t,v,l,vl = train_mnist_conv(norm=maxNormList[i])
      plt.figure(1)
      plt.plot(list(range(0,len(t))),t, label=str(maxNormList[i]))
      plt.figure(2)
      plt.plot(list(range(0,len(v))),v, label=str(maxNormList[i]))
  plt.figure(1)
  legend = plt.legend(loc='lower right', shadow=True)
  plt.title("Training Accuracy: maxNorm")
  plt.xlabel('Epoch')
  plt.ylabel('Accuracy')
  plt.savefig(path+'TrainingaccuracymaxNorm')
  plt.clf()
  plt.figure(2)
  legend = plt.legend(loc='lower right', shadow=True)
  plt.title("Validation Accuracy: maxNorm")
  plt.xlabel('Epoch')
  plt.ylabel('Accuracy')
  plt.savefig(path+'ValidationaccuracymaxNorm')
  plt.clf()
f.close()

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Train on 716 samples, validate on 180 samples
Epoch 1/36
716/716 [==============================] - 12s 16ms/sample - loss: 2.4362 - acc: 0.4818 - val_loss: 17025.2376 - val_acc: 0.3333
Epoch 2/36
716/716 [==============================] - 4s 6ms/sample - loss: 1.2762 - acc: 0.6187 - val_loss: 1441.0948 - val_acc: 0.4222
Epoch 3/36
716/716 [==============================] - 4s 6ms/sample - loss: 0.9090 - acc: 0.7151 - val_loss: 194.9026 - val_acc: 0.4444
Epoch 4/36
716/716 [==============================] - 4s 6ms/sample - loss: 0.8707 - acc: 0.7137 - val_loss: 61.2676 - val_acc: 0.4444
Epoch 5/36
716/716 [==============================] - 4s 6ms/sample - loss: 0.8746 - acc: 0.7053 - val_loss: 46.2825 - val_acc: 0.4667
Epoch 6/36
716/716 [==============================] - 4s 6ms/sample - loss: 0.8808 - acc: 0.6955 - val_loss: 17.5070 - val_acc: 0.4889
Epoch 7/36
716/716 [==============================] - 4

KeyboardInterrupt: ignored